server:
  port: 9101

eureka:
  client:
    service-url:
      defaultZone: http://bryan:123456@localhost:8763/eureka/



turbine:
  #可以让同一主机上的服务通过主机名与端口号的组合来进行区分，默认情况下会以host来区分不同的服务,这会使得在本机调试的时候，本机上的不同服务聚合成一个服务来统计
  combine-host-port: true
  #监控哪些服务
  app-config: api-zuul,micro-web
  cluster-name-expression: new String("default")
