server:
  port: 8601

spring:
  cloud:
    stream:
      rabbit:
        bindings:
          bryan_input:
             consumer:
               bindingRoutingKey: fruitKey.#  #设置一个RoutingKey信息

      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 192.168.56.101
                port: 5672
                username: admin
                password: admin
                virtual-host: /
      bindings: # 服务的整合处理
        bryan_input: # 这个名字是一个通道的名称，在分析具体源代码的时候会进行说明
          destination: BryanExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          group: bbc  # 不设置群组，默认就是一个自动删除队列
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
  application:
    name: stream-consumer

