server:
  port: 9000

spring:
  application:
    name: api-zuul


eureka:
  client:
    service-url:
      defaultZone: http://bryan:123456@localhost:8763/eureka/

  # http://localhost:9000/actuator/hystrix.stream

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

#默认不配也有路由，以服务名作为路由

# 查询所有路由信息的接口
# localhost:9000/actuator/routes


# 使用路径方式匹配路由规则。
# 参数key结构： zuul.routes.customName.path=xxx
# 用于配置路径匹配规则。
# 其中customName自定义。通常使用要调用的服务名称，方便后期管理
# 可使用的通配符有： * ** ?
# ? 单个字符
# * 任意多个字符，不包含多级路径
# ** 任意多个字符，包含多级路径
zuul:
  # 此方式相当于给所有新发现的服务默认排除zuul网关访问方式，只有配置了路由网关的服务才可以通过zuul网关访问
  # 通配方式配置排除列表。
  ignored-services: '*'
  # 通配方式配置排除网关代理路径。所有符合ignored-patterns的请求路径都不被zuul网关代理。
  ignored-patterns: /**/local/**
  #添加host头信息，标识最初的服务端请求地址
  add-host-header: true
  #默认添加  X-Forwarded-*头域
  add-proxy-headers: true
  #全局关闭重试
  retryable: false
  routes:
    micro-test:
      #关闭该服务的重试
       retryable: false
       path: /web/**
       serviceId: micro-web
      #针对某个服务传输指定的headers信息 ，默认是过滤掉 Cookie,Set-Cookie,Authorization 这三个信息的
      #这里置空就是不要过滤掉这三个
       sensitive-headers:
    micro-order:
       path: /order/**
       serviceId: micro-order
    zuul-server:
      #路由到zuul本地
      path: /local/**
      url: forward:/local
    blog:
       path: /blog/**
       url: http://localhost:8003/



# 参数key结构： zuul.routes.customName.url=xxx
# url用于配置符合path的请求路径路由到的服务地址。
#zuul.routes.micro-order.url=http://localhost:8080/

# key结构 ： zuul.routes.customName.serviceId=xxx
# serviceId用于配置符合path的请求路径路由到的服务名称。


#zuul.routes.micro-web1.path=/web/path/**
#zuul.routes.micro-web1.serviceId=micro-web-no
# ignored service id pattern
# 配置不被zuul管理的服务列表。多个服务名称使用逗号','分隔。
# 配置的服务将不被zuul代理。
#zuul.ignored-services=eureka-application-service




# prefix URL pattern 前缀路由匹配
# 配置请求路径前缀，所有基于此前缀的请求都由zuul网关提供代理。
#zuul.prefix=/api



#指定全局的headers传输，对所有路由的微服务
#zuul.sensitive-headers=Cookie,Set-Cookie,Authorization



ribbon:
   ConnectTimeout: 2000
   ReadTimeout: 5000

hystrix:
  command:
     default:
        execution:
           isolation:
              thread:
                 timeoutInMilliseconds: 100000


